// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0iE8xFsnur5uUz69V567qNqqfcaEA8k',
    appId: '1:250868432430:web:c073b281fd7a12e5eca9bf',
    messagingSenderId: '250868432430',
    projectId: 'khushboowala-f3063',
    authDomain: 'khushboowala-f3063.firebaseapp.com',
    storageBucket: 'khushboowala-f3063.firebasestorage.app',
    measurementId: 'G-E39732RPL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_RSmL770GETFQ5feFfjsnz2dEEF8pTc',
    appId: '1:250868432430:android:8dc2c1b8df733b99eca9bf',
    messagingSenderId: '250868432430',
    projectId: 'khushboowala-f3063',
    storageBucket: 'khushboowala-f3063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4UTXHVhA3maUaHKHKF8QkV_3NTPPjtY',
    appId: '1:250868432430:ios:a0639cb11f4e8a75eca9bf',
    messagingSenderId: '250868432430',
    projectId: 'khushboowala-f3063',
    storageBucket: 'khushboowala-f3063.firebasestorage.app',
    iosBundleId: 'com.example.inven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx4UTXHVhA3maUaHKHKF8QkV_3NTPPjtY',
    appId: '1:250868432430:ios:a0639cb11f4e8a75eca9bf',
    messagingSenderId: '250868432430',
    projectId: 'khushboowala-f3063',
    storageBucket: 'khushboowala-f3063.firebasestorage.app',
    iosBundleId: 'com.example.inven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX0iE8xFsnur5uUz69V567qNqqfcaEA8k',
    appId: '1:250868432430:web:dd4c49ebf8cceeabeca9bf',
    messagingSenderId: '250868432430',
    projectId: 'khushboowala-f3063',
    authDomain: 'khushboowala-f3063.firebaseapp.com',
    storageBucket: 'khushboowala-f3063.firebasestorage.app',
    measurementId: 'G-5STR29FMDF',
  );

}